notifications:
  webhooks:
    urls:
      - https://hooks-glpdevams.dev.glip.net/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6InUiLCJvaSI6IjE2ODc4MDU5NTUiLCJpZCI6Ijk2MjY0MjE5In0.tgqsQrziqobyUmLyq3MGGnLcJvRb5t4lVZEIHrEdcXQ
